AffulenceMarketReports/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from report.views import (indexView,categoryPage,publisherPage,aboutus,contactus,
                          latestReports,thankyouPage,searchReports,servicesPage)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexView, name='index'),
    path('latest-reports/', latestReports, name='latestreports'),
    path('about-us/', aboutus, name='aboutus'),
    path('contact-us/', contactus, name='contactus'),
    path('thank-you/', thankyouPage, name='thankyou'),
    path('search/', searchReports, name='searchreport'),
    path('services/', servicesPage, name='services'),

    path('category/<slug:slug>/', categoryPage, name='category'),
    path('publisher/<slug:slug>/', publisherPage, name='publisher'),
    path('industry-analysis/', include('report.urls', namespace='reports')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/urls.py
from django.urls import path
from report.views import reportPage,requestSample,checkout,requestInquiry,requestDiscount
app_name = 'reports'

urlpatterns = [

    path('<slug:slug>/', reportPage, name='reportpage'),
    path('request-sample/<int:id>/', requestSample, name='samplerequest'),
    path('request-discount/<int:id>/', requestDiscount, name='discountrequest'),
    path('request-inquiry/<int:id>/', requestInquiry, name='inquiryrequest'),
    path('checkout/<int:id>/', checkout, name='checkout'),


]

templates/base/about-us.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="container">
    		<div class="text-center">
				<h1 class="head-after h1fs">About Us</h1>
			</div>
		<div class="row">
		  <div class="col-lg-12">
			<div class="row">
				<div class="text-justify tab-content" id="aboutt">
					<p>Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.

Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.</p>

					<p>Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.

Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring.</p>

					<p><b>Some Questinary</b></p>
						<ul>
							<li>Blah Blah </li>

						</ul>
					<p><b>Our Vision</b></p>
						<ul>
							<li>table win-win survival strategies to ensure proactive dominatio</li>
							<li>table win-win survival strategies to ensure proactive dominatio</li>
							<li>table win-win survival strategies to ensure proactive dominatio</li>
						</ul>

						<br>
				<p> <b>Capitalize on low hanging fruit to identify a ball-park value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps</b></p>
				</div>
				 <div class="clearfix">&nbsp;</div>
			</div>
		  </div>

		</div>
    </div>

{% endblock %}

templates/base/contact-us.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="container">
			<div class="text-center">
				<h1 class="head-after h1fs">Contact Us</h1>
			</div>

		<div class="row">
				<div class="col-lg-8">
					<div class="card">
					  <div class="card-header" style="background-color:#ff0000;">
						 <h3 style="color:white;">Get in touch with us </h3>
					  </div>
					  <div class="card-body">
						<form method="post">
							<h3>*{{form.errors}}</h3>
						{% csrf_token %}
						{{form.full_name}}
						{{form.corporate_email}}
						{{ form.phone }}
						{{ form.subject }}
						{{ form.message }}

						<button type='submit' class='btn btn-primary'><strong>Send</strong></button>


					 </form>

					  </div>
					</div>
				</div>


		<div class="col-lg-4">
			      <div class="card">

							<div class="card-header" style="background-color:#ff0000;">
						 <h3 style="color:white;">Get in touch with us </h3>
					  </div>
					  <div class="card-body">
						  <p>Location Address:</p>
					  </div>

	   </div>

</div>
		</div>
	</div>
{% endblock %}

templates/base/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>CSS Overlaying One DIV over Another DIV</title>
<style>
    .container{
        width: 200px;
        height: 200px;
        position: relative;
        margin: 20px;
    }
    .box{
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0;
        left: 0;
        opacity: 0.8;  /* for demo purpose  */
    }
    .stack-top{
        z-index: 9;
        margin: 20px; /* for demo purpose  */
    }
</style>
</head>
<body>
    <div class="container">
        <div class="box" style="background: red;"></div>
        <div class="box stack-top" style="background: blue;"></div>
    </div>
</body>
</html>

templates/base/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
    <style>
        body,html {
  background: #007bff;
  height:100%;
}
h1 {
  height:auto;
  display:table;
  width: 80%;
  text-align:center;
  overflow: auto;
  margin: auto;
  position: absolute;
  top: 0;left: 0;bottom: 0;right: 0;
  color: white;
  font-family: 'Raleway', sans-serif;
  font-weight:300;
  font-size:3em;
}

h2 {
    position: fixed;
    text-align:center;
    top:10px;
    right:20px;
    color:white;
    font-size: 20px;
    font-family: Roboto;
    font-weight: normal;
		z-index:999;
    span{
      font-size:15px;
      font-weight: lighter;
    }
    a{
      color:white;
      font-size:15px;
      padding: 0 30px

    }
  }
    </style>
</head>
<body>
<h1>Jquery & CSS3 background</h1>

<h2><span>by</span> Enrico Toniato <a href="http://enricotoniato.com" target="_blank">enricotoniato.com</a></h2>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://ricostacruz.com/jquery.transit/jquery.transit.min.js"></script>
<script>
   var background = {}

  background.initializr = function (){

    var $this = this;



    //option
    $this.id = "background_css3";
    $this.style = {bubbles_color:"#fff",stroke_width:0, stroke_color :"black"};
    $this.bubbles_number = 30;
    $this.speed = [1500,8000]; //milliseconds
    $this.max_bubbles_height = $this.height;
    $this.shape = false // 1 : circle | 2 : triangle | 3 : rect | false :random

    if($("#"+$this.id).lenght > 0){
      $("#"+$this.id).remove();
    }
    $this.object = $("<div style='z-inde:-1;margin:0;padding:0; overflow:hidden;position:absolute;bottom:0' id='"+$this.id+"'> </div>'").appendTo("body");

    $this.ww = $(window).width()
    $this.wh = $(window).height()
    $this.width = $this.object.width($this.ww);
    $this.height = $this.object.height($this.wh);


    $("body").prepend("<style>.shape_background {transform-origin:center; width:80px; height:80px; background: "+$this.style.bubbles_color+"; position: absolute}</style>");


    for (i = 0; i < $this.bubbles_number; i++) {
        $this.generate_bubbles()
    }

  }





   background.generate_bubbles = function() {
     var $this = this;
     var base = $("<div class='shape_background'></div>");
     var shape_type = $this.shape ? $this.shape : Math.floor($this.rn(1,3));
     if(shape_type == 1) {
       var bolla = base.css({borderRadius: "50%"})
     }else if (shape_type == 2){
       var bolla = base.css({width:0, height:0, "border-style":"solid","border-width":"0 40px 69.3px 40px","border-color":"transparent transparent "+$this.style.bubbles_color+" transparent", background:"transparent"});
     }else{
       var bolla = base;
     }
     var rn_size = $this.rn(.8,1.2);
     bolla.css({"transform":"scale("+rn_size+") rotate("+$this.rn(-360,360)+"deg)", top:$this.wh+100, left:$this.rn(-60, $this.ww+60)});
     bolla.appendTo($this.object);
     bolla.transit({top: $this.rn($this.wh/2,$this.wh/2-60), "transform":"scale("+rn_size+") rotate("+$this.rn(-360,360)+"deg)", opacity: 0},$this.rn($this.speed[0],$this.speed[1]), function(){
       $(this).remove();
       $this.generate_bubbles();
     })

    }


background.rn = function(from, to, arr) {
  if(arr){
          return Math.random() * (to - from + 1) + from;
  }else{
    return Math.floor(Math.random() * (to - from + 1) + from);
  }
    }
background.initializr()
</script>
</body>
</html>

templates/base/partial-result.html
     {% if searchreports %}
     <div class="searchdiv" style="overflow-y: scroll;position: absolute;z-index: 99;max-height: 300px;">
     <table class="table table-bordered table-hover" style="background-color:#ff0000">

			 {% for report in searchreports %}
           <tr>
               <td> <a href="{% url 'reports:reportpage' report.slug %}" style="color:white;">{{ report.title }}</a></td>
           </tr>
			 {% endfor %}

     </table>
     </div>
			{% else %}
<!--		  <p>No Report found.</p>-->
     {% endif %}

     <script type="text/javascript">
        $(document).mouseup(function (e) {
            if ($(e.target).closest(".searchdiv").length === 0) {
                $(".searchdiv").hide();
            }
        });
    </script>

templates/base/services.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<div class="text-center"><input type="hidden" id="catpage" value="1">
<h1 class="head-after h1fs">Services Page</h1>
	<div class="text-justify" id="aboutt">
	<p>Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.</p>
	
	<p>Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.to work with a wide number of companies from mid-size organizations to industry leaders in order to propel their business forward with confidence.</p>
	
	<p>Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.Market Insights significantly enhances overall performance, helps in overcoming business challenges, enables cost savings, increases througLeverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.executing new strategies.</p>
	
	<p><b>Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.ge in a market space by offering consulting services that include—but are not limited to:</b></p>
		<ul>
			<li>table win-win survival strategies to ensure proactive dominatio</li>
			<li>table win-win survival strategies to ensure proactive dominatio</li>
			<li>table win-win survival strategies to ensure proactive dominatio</li>
			<li>table win-win survival strategies to ensure proactive dominatio</li>
			<li>table win-win survival strategies to ensure proactive dominatio</li>
			<li>table win-win survival strategies to ensure proactive dominatio</li>

		</ul>
</div>
</div>

</div>
{% endblock %}

templates/base/thank-you.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="container">
    	<div class="jumbotron text-center">
              <h1 class="display-3">Thank You!!</h1>
              <p class="lead"><strong>Our Sales Representitive will soon get Back to you.</strong> </p>
              <hr>
              <p>
                Having trouble? <a href="{% url 'contactus' %}" style="color:blue">Contact us</a>
              </p>
              <p class="lead">
                <a class="btn btn-primary " href="{% url 'index' %}" role="button">Continue to homepage</a>
              </p>
            </div>
    </div>
{% endblock %}