AffulenceMarketReports/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from report.views import (indexView,categoryPage,publisherPage,aboutus,contactus,
                          latestReports,thankyouPage,searchReports,servicesPage)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexView, name='index'),
    path('latest-reports/', latestReports, name='latestreports'),
    path('about-us/', aboutus, name='aboutus'),
    path('contact-us/', contactus, name='contactus'),
    path('thank-you/', thankyouPage, name='thankyou'),
    path('search/', searchReports, name='searchreport'),
    path('services/', servicesPage, name='services'),

    path('category/<slug:slug>/', categoryPage, name='category'),
    path('publisher/<slug:slug>/', publisherPage, name='publisher'),
    path('industry-analysis/', include('report.urls', namespace='reports')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

report/urls.py
from django.urls import path
from report.views import reportPage,requestSample,checkout,requestInquiry,requestDiscount
app_name = 'reports'

urlpatterns = [

    path('<slug:slug>/', reportPage, name='reportpage'),
    path('request-sample/<int:id>/', requestSample, name='samplerequest'),
    path('request-discount/<int:id>/', requestDiscount, name='discountrequest'),
    path('request-inquiry/<int:id>/', requestInquiry, name='inquiryrequest'),
    path('checkout/<int:id>/', checkout, name='checkout'),


]

report/forms.py
from django import forms
from .models import Lead,Billing_Details,Contact_Us
from django_countries.widgets import CountrySelectWidget



class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact_Us
        fields = ['full_name','corporate_email','phone','subject','message']
        widgets ={

            'full_name': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder' : "  Full Name",
                    'name':'fullname',
                }
            ),
            'corporate_email': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Corpoarate Email",
                    'name':'email',
                }
            ),
            'phone': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Phone No.",
                    'name':'phone',
                }
            ),
            'subject': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Subject",
                    'name':'subject',
                }
            ),
            'message': forms.Textarea(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Do you have any specific field of intrest? please suggest us",
                    'rows': '3',
                    'cols': '40',
                    'name':'comment',

                }
            ),
        }

class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ['full_name','corporate_email','country','phone','job_title','company','comment']
        widgets = {
            'country': forms.Select(
                attrs={
                    'class': 'form-control mb-2',
                    'name': 'country',
                }
            ),
            'full_name': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder' : "  Full Name",
                    'name':'fullname',
                }
            ),
            'corporate_email': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Corpoarate Email",
                    'name':'email',
                }
            ),
            'phone': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Phone No.",
                    'name':'phone',
                }
            ),
            'job_title': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Job Title",
                    'name':'job_title',
                }
            ),
            'company': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Company",
                    'name':'company',
                }
            ),
            'comment': forms.Textarea(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Do you have any specific field of intrest? please suggest us",
                    'rows': '3',
                    'cols': '40',
                    'name':'comment',

                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Last Name",
                    'name': 'lastname',
                }
            ),
        }


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Billing_Details
        exclude = ['report']
        widgets = {
            'country': forms.Select(
                attrs={
                    'class': 'form-control mb-2',
                    'name': 'country',
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  First Name",
                    'name': 'First Name',
                }
            ),
            'corporate_email': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Corpoarate Email",
                    'name': 'email',
                }
            ),
            'phone': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Phone No.",
                    'name': 'phone',
                }
            ),
            'job_title': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Job Title",
                    'name': 'job_title',
                }
            ),
            'company': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Company",
                    'name': 'company',
                }
            ),
            'address': forms.Textarea(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Address",
                    'rows': '3',
                    'cols': '40',
                    'name': 'address',

                }
            ),
            'city': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  City",
                    'name': 'city',
                }
            ),
            'state': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  State",
                    'name': 'state',
                }
            ),
            'zipcode': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Zip Code",
                    'name': 'zipcode',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': "  Last Name",
                    'name': 'lastname',
                }
            )
        }

report/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.template.loader import render_to_string

from .forms import LeadForm,CheckoutForm,ContactForm
from .models import Category,Report,Publisher
from django_countries import countries
from django.core.mail import send_mail
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.http import JsonResponse



def indexView(request):
    reports = Report.objects.all()[:3]
    categories = Category.objects.all()
    query = request.GET.get('searchReport')
    print(query)
    return render(request,'base/index.html',{'reports': reports,'categories':categories})


def aboutus(request):
    return render(request,'base/about-us.html')

def servicesPage(request):
    return render(request,'base/services.html')

def contactus(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('thankyou')
    return render(request,'base/contact-us.html',{'form':form})


def reportPage(request,slug):
    report = get_object_or_404(Report, slug=slug)
    category = report.category
    return render(request,'report/reportpage.html',{'report':report,'category':category})

def thankyouPage(request):
    return render(request,'base/thank-you.html')


def requestSample(request,id):
    report = get_object_or_404(Report, id=id)
    if request.method == 'POST':
        form = LeadForm(request.POST)

        if form.is_valid():
            lead_form=form.save(commit=False)
            lead_form.report = report
            lead_form.request_type = 'Request Sample'
            if request.POST['comment'] == "":
                lead_form.comment = ""

            lead_form.save()

            emailBody = 'Report Name:'+ report.title + '\n\n' + 'Client Name:' + lead_form.full_name + '\n\n' 'Client Email:'+ lead_form.corporate_email + '\n\n' + 'Phone:' + str(lead_form.phone) + '\n\n' + 'Country:' + str(lead_form.country) +'\n\n' + 'Category:'+ report.category.name +'\n\n'+'Publisher :'+report.publisher.name+ '\n\n' +'Company:' + lead_form.company + '\n\n' + 'Job Title:' + lead_form.job_title +'\n\n' +'Price:' + str(report.single_user_price) +'\n\n' +'Comments:' + lead_form.comment
            send_mail(
                'Lead - Sample Request',
                 emailBody,
                'sales@affluencemarketreports.com',
                ['sales@affluencemarketreports.com'],
                fail_silently=False,
            )
            return redirect('thankyou')
        else:
            print('Form invalid')
    else:
        form = LeadForm()
    return render(request, 'report/request-sample.html', {'form':form,'report':report})

def requestDiscount(request,id):
    report = get_object_or_404(Report, id=id)
    if request.method == 'POST':
        form = LeadForm(request.POST)
        if form.is_valid():
            lead_form=form.save(commit=False)
            lead_form.report = report
            lead_form.request_type = 'Request Discount'
            if request.POST['comment'] == "":
                lead_form.comment = ""
            lead_form.save()
            emailBody = 'Report Name:'+ report.title + '\n\n' + 'Client Name:' + lead_form.full_name + '\n\n' 'Client Email:'+ lead_form.corporate_email + '\n\n' + 'Phone:' + str(lead_form.phone) + '\n\n' + 'Country:' + str(lead_form.country) +'\n\n' + 'Category:'+ report.category.name +'\n\n'+'Publisher :'+report.publisher.name+ '\n\n' +'Company:' + lead_form.company + '\n\n' + 'Job Title:' + lead_form.job_title +'\n\n' +'Price:' + str(report.single_user_price) +'\n\n' +'Comments:' + lead_form.comment
            send_mail(
                'Lead - Discount Request',
                 emailBody,
                'sales@affluencemarketreports.com',
                ['sales@affluencemarketreports.com'],
                fail_silently=False,
            )
            return redirect('thankyou')
        else:
            print('Form invalid')
    else:
        form = LeadForm()
    return render(request, 'report/request-discount.html', {'form':form,'report':report})

def requestInquiry(request,id):
    report = get_object_or_404(Report, id=id)
    if request.method == 'POST':
        form = LeadForm(request.POST)
        if form.is_valid():
            lead_form=form.save(commit=False)
            lead_form.report = report
            lead_form.request_type = 'Request Inquiry'
            if request.POST['comment'] == "":
                lead_form.comment = ""
            lead_form.save()
            emailBody = 'Report Name:'+ report.title + '\n\n' + 'Client Name:' + lead_form.full_name + '\n\n' 'Client Email:'+ lead_form.corporate_email + '\n\n' + 'Phone:' + str(lead_form.phone) + '\n\n' + 'Country:' + str(lead_form.country) +'\n\n' + 'Category:'+ report.category.name +'\n\n'+'Publisher :'+report.publisher.name+ '\n\n' +'Company:' + lead_form.company + '\n\n' + 'Job Title:' + lead_form.job_title +'\n\n' +'Price:' + str(report.single_user_price) +'\n\n' +'Comments:' + lead_form.comment
            send_mail(
                'Lead - Inquiry Before Buying Request',
                 emailBody,
                'sales@affluencemarketreports.com',
                ['sales@affluencemarketreports.com'],
                fail_silently=False,
            )
            return redirect('thankyou')
        else:
            print('Form invalid')
    else:
        form = LeadForm()
    return render(request, 'report/request-inquiry.html', {'form':form,'report':report})


def checkout(request, id):
    report = get_object_or_404(Report, id=id)
    if request.method == 'POST':
       price = request.POST['price']

    form = CheckoutForm()
    return render(request,'report/checkout.html',{'report':report,'form':form,'price':price})


def categoryPage(request, slug):
    category = get_object_or_404(Category, slug=slug)
    reports = Report.objects.filter(category=category)
    all_categories = Category.objects.all()

    paginator = Paginator(reports, 2)
    page_number = request.GET.get('page')
    try:
        reports = paginator.page(page_number)
    except PageNotAnInteger:
        reports = paginator.page(1)
    except EmptyPage:
        reports = paginator.page(paginator.num_pages)
    return render(request, 'report/category.html', {'category': category, 'reports': reports, 'all_categories': all_categories})


def publisherPage(request, slug):
    publisher = get_object_or_404(Publisher,slug=slug)
    reports = Report.objects.filter(publisher=publisher)
    all_publishers = Publisher.objects.all()
    paginator = Paginator(reports, 2)
    page_number = request.GET.get('page')
    try:
        reports = paginator.page(page_number)
    except PageNotAnInteger:
        reports = paginator.page(1)
    except EmptyPage:
        reports = paginator.page(paginator.num_pages)
    return render(request,'report/publisher.html', {'publisher':publisher,'reports': reports, 'all_publishers': all_publishers})

def latestReports(request):
    reports = Report.objects.all().order_by('-published_date')
    all_categories = Category.objects.all()
    paginator = Paginator(reports, 5)
    page_number = request.GET.get('page')
    try:
        reports = paginator.page(page_number)
    except PageNotAnInteger:
        reports = paginator.page(1)
    except EmptyPage:
        reports = paginator.page(paginator.num_pages)
    return render(request,'report/latest-report.html',{'reports':reports,'all_categories':all_categories})


def searchReports(request):
    ctx = {}
    url_parameter = request.GET.get("q")
    if url_parameter:
        searchreports = Report.objects.filter(title__icontains=url_parameter)
    else:
        searchreports = Report.objects.all()

    ctx["searchreports"] = searchreports

    if request.is_ajax():
        html = render_to_string(
            template_name="base/partial-result.html",
            context={"searchreports": searchreports}
        )
        data_dict = {"html_from_view": html}
        return JsonResponse(data=data_dict, safe=False)

    return render(request, 'base/index.html',ctx)

templates/report/reportpage.html
{% extends 'base.html'%}
{% load static %}


{% block body %}


<style>#top-header{margin:0 0 10px 0}.header-fixed{position:fixed;width:100%;background-color:#f1f1f1;top:0;z-index:999;box-shadow:0 0 20px 0 #ddd}</style><div id="body-container">
<div class="container">
    <div class="row">
<div class="col-lg-9 col-12 reportdet">
<div class="breadcum_list">
<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'category' category.slug %}">{{report.category.name}}</a></li>
<li class="breadcrumb-item active" aria-current="page">{{report.meta_title | title }}</li>
</ol>
</nav>
</div>
<div class="media_box mb-2">
<div class="media ">
<img src="{% static 'images/bookcover.png' %}" height="200px" width="170px" alt="Market Research Report" title="Market Research Report" class="align-self-start mr-4 d-none d-sm-block img-responsive">
<div class="media-body" >
  <h1 class="rd-page-title">
	{{report.title}}	</h1>
	<ul class="list-inline rd-cat">
	<li class="list-inline-item"><b>Report Id</b> : {{report.id}}</li>
	<li class="list-inline-item"><b>Pages</b> : {{report.no_of_pages}}</li>	<li class="list-inline-item"><b>Date</b> : May, 2020</li>
	<li class="list-inline-item"><b>Category</b> : <a href="{% url 'category' report.category.slug %}">{{report.category.name | capfirst }}</a></li>
		<li><span><b>Publisher</b> : {{report.publisher.name}}</span></li>
	</ul>
	<div id="calltoac">
        <a href="{% url 'reports:samplerequest' report.id%}"><button class="btn btn-success"><span><i class="fas fa-download"></i> &nbsp; <strong>Download Sample</strong></span></button></a>
        <a href="{% url 'reports:discountrequest' report.id %}"><button class="btn btn-danger"><span><i class="fas fa-percentage"></i> &nbsp; <strong>Request Discount</strong></span></button> </a>
        <a href="{% url 'reports:inquiryrequest' report.id %}"><b><button class="btn btn-info"><span><i class="fas fa-headset"></i> &nbsp; <strong>Inquire Before Buy</strong></span></button> </b> </a>

	</div>
</div>
</div>
</div>


<div class="clearfix">&nbsp;</div>
<ul class="nav nav-pills rep-det-tabs" id="pills-tab" role="tablist">
<li class="nav-item">
	<a class="nav-link active" id="rep-overview-tab" data-toggle="pill" href="#rep-overview" role="tab" aria-controls="rep-overview" aria-selected="true">Report Summary</a>
</li>
<li class="nav-item">
	<a class="nav-link" id="rep-toc-tab" data-toggle="pill" href="#rep-toc" role="tab" aria-controls="rep-toc" aria-selected="false">Table of Content</a>
</li>
<li class="nav-item">
	<a class="nav-link" id="rel-rep-tab" data-toggle="pill" href="#rel-rep" role="tab" aria-controls="rel-rep" aria-selected="false">Related Reports</a>
</li>


</ul>
<div class="tab-content rep-rd-content tab-wrapper" id="pills-tabContent">
<div class="tab-pane fade active show" id="rep-overview" role="tabpanel" aria-labelledby="rep-overview-tab">

<p>{{report.summary | safe | linebreaks }}</p>

</div>
<div class="tab-pane fade" id="rep-toc" role="tabpanel" aria-labelledby="rep-toc-tab">
	{{report.tabel_of_content | safe | linebreaks }}</div>
<div class="tab-pane fade" id="rel-rep" role="tabpanel" aria-labelledby="rel-rep-tab"> 
<div class="row">
 <div class="col-lg-12">
 <article class="post reportsList">
 	 <div class="panel panel-default">
	  <div class="panel-body">
	  <div class="row">
	  <div class="col-lg-3 col-sm-3">
	  <div class="reportsImg">
	  <a href="#"> <img src="{% static 'images/market-report.jpg' %}" height="200px" width="170px"  alt="Market Research Report" title="Market Research Report" class="img-post img-responsive"></a>
	 </div>
	</div>
	<div class="col-lg-9 col-sm-9 post-content">
		<h3 class="post-title reportsTitle">
		<a href="#" class="transicion">Cell Culture Market 2020 By Manufacturers, Regions, Types, Applications And Forecast To 2026</a>
		</h3>
		<div class="reportsContent">
		<table class="table table-bordered">
		<tbody><tr>
		   <td> <i class="fa fa-user"></i> &nbsp; Price : US $3000</td>
		    
		   <td><i class="fa fa-calendar"></i> &nbsp; Date : May 2020</td>
		</tr>
		<tr>
		<td><i class="fa fa-user"></i> &nbsp; Category : <a href="#"> Medical Devices</a></td>
		<td><i class="fa fa-file"></i> &nbsp;  Pages : 115</td>
		</tr>
		</tbody></table>
		 <a class="btn btn-primary vert btn btn-primary" href="#">View Details
		</a>
		</div>
			
	   </div>
	  </div>
	 </div>
	</div>

	</article>
</div>
</div>
</div>
</div>
<div class="clearfix">&nbsp;</div>
</div>
<div class="col-lg-3 col-md-12 col-sm-12 mt-5">

          <div class="card">
                  <div class="card-header" style="background-color:#ff0000;color:white">
                      <strong>Choose License Type</strong>
                  </div>
                  <div class="card-body" >
                      <form method="post" action="{% url 'reports:checkout' report.id %}">
                          {% csrf_token %}
                      <p class="card-text"><input type="radio" name="price" checked="checked" value="{{report.single_user_price}}"> Single User :   <strong>${{report.single_user_price}}</strong></p>
                    <hr>
                          <p class="card-text" ><input type="radio" name="price" value="{{report.multi_user_price}}"> Multi User : <strong>${{report.multi_user_price}}</strong></p>
                      <hr style="color:#ff0000;" >
                          <p class="card-text" ><input type="radio" name="price" value="{{report.corporate_user_price}}"> Corporate User : <strong>${{report.corporate_user_price}}</strong></p>
                     <hr style="color:white;">
<!--       <button type="submit" class="btn btn-primary btn-block" style="background-color:#f39c12; border-color:#f39c12"><i class="fas fa-shopping-cart"></i>&nbsp;<strong>Buy Now</strong></button>-->
                       <button type="submit" class="button-animated btn-block"><i class="fas fa-shopping-cart"></i>&nbsp;<strong>Buy Now</strong></button>
                      </form>
                  </div>
          </div>
          <div class="card">
                  <div class="card-header" style="background-color:#ff0000;color:white">
                      <strong>Why Choose Us ?</strong>
                  </div>
                  <div class="card-body" >

                      <p class="card-text">SOme Text</p>
                      <p class="card-text">SOme Text</p>
                      <p class="card-text">SOme Text</p>
                      <p class="card-text">SOme Text</p>


                  </div>
          </div>
    <div class="card">
                  <div class="card-header" style="background-color:#ff0000;color:white">
                      <strong>Need Assistance</strong>
                  </div>
                  <div class="card-body" >

                      <p class="card-text">SOme Text</p>
                      <p class="card-text">SOme Text</p>
                      <p class="card-text">SOme Text</p>
                      <p class="card-text">SOme Text</p>


                  </div>
          </div>


     </div>
</div>
</div>
<div class="FAQsect">
<div class="inner-wrapper">
<div class="container-fluid">
	<div class="accordion-option">
	<h3 class="title">Frequently Asked Questions</h3>
	<a href="javascript:void(0)" class="toggle-accordion active" accordion-id="#accordion"></a>
  </div>
  <div class="clearfix"></div>
  <div class="panel-group FAQaccordion" id="accordion" role="tablist" aria-multiselectable="true">

    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          What is the scope of the report?
        </a>
      </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse in collapse show" role="tabpanel" data-parent="#accordion" aria-labelledby="headingOne">
        <div class="panel-body">
          The report efficiently evaluates the market from various dimensions to deliver an end-product that is informative, elaborate, and accurate and includes <b> detailed market segmentation, regional analysis, and competitive landscape of the industry.</b>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingTwo">
        <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
         Does this report estimates the current market size?
        </a>
      </h4>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel" data-parent="#accordion" aria-labelledby="headingTwo">
        <div class="panel-body">
          The report efficiently evaluates the current market size and provides industry forecast. The market was valued at xx Million US$ in 2019, and is expected to grow at a CAGR of xx% during the period 2020-2027.
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingThree">
        <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Does the report provides Market Size in terms of – Value (US$ Mn) and Volume (thousand ton / metric ton / cubic meter) - of the market?
        </a>
      </h4>
      </div>
      <div id="collapseThree" class="panel-collapse collapse in" role="tabpanel" data-parent="#accordion" aria-labelledby="headingThree">
        <div class="panel-body">
          The report efficiently evaluates the current market size and provides forecast for the industry in terms of <b> Value (US$ Mn) and Volume (thousand ton / metric ton / cubic meter). </b>
        </div>
     </div>
    </div>
	<div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingThree">
        <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
			Which segments covered in this report?
        </a>
      </h4>
      </div>
      <div id="collapseThree" class="panel-collapse collapse in" role="tabpanel" data-parent="#accordion" aria-labelledby="headingThree">
        <div class="panel-body">
          Market is segmented by Types, Applications, Technology, End-use Industries, and Regions. 
        </div>
     </div>
    </div>
	
   <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingThree">
        <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
			What are the key factors covered in this report?
        </a>
      </h4>
      </div>
      <div id="collapseThree" class="panel-collapse collapse in" role="tabpanel" data-parent="#accordion" aria-labelledby="headingThree">
        <div class="panel-body">
         The report presents the <b> current market size, and market forecast, market opportunities, key drivers and restraints, regulatory scenario, industry trend, PESTLE analysis, PORTER’s analysis, new product approvals/launch, promotion and marketing initiatives, pricing analysis, export-import analysis, trade analysis, competitive landscape </b> which help businesses in decision making. The analysis data is based on current and historical market trends which help in investment related decisions.  
        </div>
     </div>
    </div>
	
	<div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingThree">
        <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
			Does this report offer customization?
        </a>
      </h4>
      </div>
      <div id="collapseThree" class="panel-collapse collapse in" role="tabpanel" data-parent="#accordion" aria-labelledby="headingThree">
        <div class="panel-body">
          Custom research is crucial components of the business strategy which helps any organization to gain insight into specific business sector, aligned with specific area of interest. Thus, SMI offers more accurate, pragmatic, and actionable information specifically tailored to suit your business needs. 
        </div>
     </div>
    </div>

  </div>
</div>   
</div>
</div>
</div>
{% endblock %}